# Generated by Django 2.2.3 on 2019-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QueryType', models.CharField(max_length=250)),
                ('Related', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionKeywords', models.CharField(max_length=500)),
                ('Response', models.CharField(max_length=1000)),
                ('ResponseLink', models.SmallIntegerField(max_length=5)),
            ],
        ),
    ]
