# Generated by Django 2.2.3 on 2019-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ResponseLink',
            field=models.IntegerField(max_length=10),
        ),
    ]
