# Generated by Django 2.2.3 on 2019-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190730_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.AlterField(
            model_name='questions',
            name='ResponseLink',
            field=models.IntegerField(),
        ),
    ]
