# Generated by Django 2.2.3 on 2019-08-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190806_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Attachment',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
