# Generated by Django 2.2.3 on 2019-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_questions_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='QuestionKeywords',
            field=models.BinaryField(max_length=500),
        ),
    ]
