# Generated by Django 2.2.3 on 2019-08-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190819_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='QuestionKeywords',
            field=models.CharField(max_length=500),
        ),
    ]
