# Generated by Django 2.2.3 on 2019-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_questions_minmatchscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='FuzzyResponse',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Response',
            field=models.CharField(max_length=2500),
        ),
    ]
